"""add activities, rates, visitor_activities, accommodations

Revision ID: 410b08ccf4f6
Revises: 53d10eb5c093
Create Date: 2026-08-21 15:26:48.091079
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '410b08ccf4f6'
down_revision: Union[str, None] = '53d10eb5c093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_code'), ['code'], unique=True)

    op.create_table('accommodations',
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('facility', sa.String(length=128), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_station_id', sa.String(length=64), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accommodations_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('activity_rates',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('FNR', 'FR', 'ROA', 'EAC', name='visitorcategory', native_enum=False, length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'category', name='uq_activity_rate_activity_category')
    )
    with op.batch_alter_table('activity_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_rates_activity_id'), ['activity_id'], unique=False)

    op.create_table('visitor_activities',
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('FNR', 'FR', 'ROA', 'EAC', name='visitorcategory', native_enum=False, length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount_minor', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_station_id', sa.String(length=64), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_activities_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_activities_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_activities_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_activities_activity_id'))

    op.drop_table('visitor_activities')
    with op.batch_alter_table('activity_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_rates_activity_id'))

    op.drop_table('activity_rates')
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accommodations_visitor_id'))

    op.drop_table('accommodations')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_code'))

    op.drop_table('activities')
    # ### end Alembic commands ###
