"""add visits table

Revision ID: 53d10eb5c093
Revises: aba24b6d205f
Create Date: 2026-08-21 15:11:32.074754
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53d10eb5c093'
down_revision: Union[str, None] = 'aba24b6d205f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('entry_gate', sa.String(length=64), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_officer_id', sa.Uuid(), nullable=True),
    sa.Column('ticket_number', sa.String(length=64), nullable=False),
    sa.Column('nights_purchased', sa.Integer(), nullable=False),
    sa.Column('exit_gate', sa.String(length=64), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_officer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_station_id', sa.String(length=64), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visitor_id'))

    op.drop_table('visits')
    # ### end Alembic commands ###
