"""add sync_operations and sync_exceptions

Revision ID: baf1d24a0db6
Revises: 410b08ccf4f6
Create Date: 2026-08-21 15:35:42.614123
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'baf1d24a0db6'
down_revision: Union[str, None] = '410b08ccf4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_exceptions',
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_operations',
    sa.Column('op_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('op_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_operations')
    op.drop_table('sync_exceptions')
    # ### end Alembic commands ###
